config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  namespace :admin do
    get 'dashboard' => 'dashboard#dashboard', as: :dashboard
  end

  resources :articles
  resources :books
  resources :photos
  resources :posts
  resources :users
  resources :essays
  resources :lectures

  get 'home' => 'home#welcome', as: :home
  get 'about' => 'home#about', as: :about

  get 'sign_in' => 'sessions#new', as: :sign_in
  post 'sign_in' => 'sessions#create'
  delete 'sign_in' => 'sessions#delete', as: :end_session
  get 'sign_out' => 'sessions#delete', as: :sign_out

  root 'home#welcome'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/essay.rb
class Essay < ApplicationRecord
end

app/models/lecture.rb
class Lecture < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
  end

  def create
    @book=Book.create(book_params)
    if @book.save
      redirect_to admin_dashboard_path, notice: "Book Successfully Added"
    else
      render :new
    end
  end

  def index
    @books = Book.all
  end

  def show
    @book = Book.find_by id: params[:id]
  end

  def edit
    @book = Book.find_by id: params[:id]
  end

  def update
    @book = Book.find_by id: params[:id]
    if @book.update(book_params)
      redirect_to admin_dashboard_path, notice: "Book Details Successfully Updated"
    else
      render :edit
    end
  end

  def delete
      @book = Book.find_by id: params[:id]
      @book.destroy
      redirect_to admin_dashboard_path, notice: 'Book Details Removed'
  end

  private

  def book_params
    params.require(:book).permit(:full_title, :title, :sub_title, :year, :contributors, :publisher, :language, :pages, :description, :amazon_link, :height, :width, :photo_link)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/essays_helper.rb
module EssaysHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <ul>
           <a href="https://www.facebook.com/naomi.pollock.9"><i class="fa fa-facebook
             fa-2x" aria-hidden="true"></i></a>

             <a href="https://www.instagram.com/sweathesmallstuff/"><i class="fa fa-instagram fa-2x" aria-hidden="true"></i></a>

             <a href="mailto:sdossettswift@gmail.com?subject=GettingInTouch"><i class="fa fa-envelope fa-2x" aria-hidden="true"></i> </a>
 </ul>
</div>

app/views/layouts/_header.html.erb
     <h1><%= link_to 'NAOMI POLLOCK', root_path%></h1>


    <ul>
      <li><%= active_link_to "BOOKS", books_path%></li>
      <li><%= active_link_to "ARTICLES", articles_path%></li>
      <li><%= active_link_to "LECTURES", lectures_path%></li>
      <li><%= active_link_to "BLOGS", posts_path%></li>
      <li><%= active_link_to "ABOUT", about_path%></li>
      <li><%= active_link_to "INSTAGRAM", photos_path%></li>
      <li id="search-block"><%= form_tag(posts_path, :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "     S E A R C H" %>
          <% end %></li>
    </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NAOMI POLLOCK</title>
    <%= csrf_meta_tags %>
    <script type="text/javascript">
      = javascript_include_tag Ckeditor.cdn_url
    </script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <div class="body">
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>